const sidebars = {
  mainSidebar: [{ type: "autogenerated", dirName: "." }],
  elementsSidebar: [
    { type: "autogenerated", dirName: "packages/atomic-elements/docs" },
  ],
  formsSidebar: [{ type: "autogenerated", dirName: "packages/forms/docs" }],
  hooksSidebar: [{ type: "autogenerated", dirName: "packages/hooks/docs" }],
  ltiClientSidebar: [
    { type: "autogenerated", dirName: "packages/lti-client/docs" },
  ],
  canvasClientSidebar: [
    { type: "autogenerated", dirName: "packages/canvas-client/docs" },
  ],
};

export default sidebars;
