const sidebars =  {
  mainSidebar: [{ type: "autogenerated", dirName: "." }],
  elementsSidebar: [
    { type: "autogenerated", dirName: "packages/atomic-elements/docs" },
  ],
  formsSidebar: [{ type: "autogenerated", dirName: "packages/forms/docs" }],
  hooksSidebar: [{ type: "autogenerated", dirName: "packages/hooks/docs" }],
};

export default sidebars;
