name: Deploy Storybook to GitHub Pages

on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tags
        run: git fetch --tags origin
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Install dependencies
        run: yarn ci
      - name: Build Storybook
        run: yarn docs:build ${{ steps.get_tag.outputs.TAG }}
      - name: Deploy Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          commit_message: ${{ steps.get_tag.outputs.TAG }}
          keep_files: true
