name: Jest Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - next
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Install Yarn
        run: corepack prepare yarn@stable --activate

      - name: Activate Yarn
        run: yarn set version 3.6.4

      - name: Install Node.js dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
